### ISSUE TITLE
Manjaro logo occupies strange amount of horizontal space

### ISSUE THREAD

**Issue by jamesrobb** [dylanaraps/neofetch#1175]
## Description

Recently the manjaro logo seems to occupy an unusual amount of horizontal space compared to other distro logos. I noticed this maybe a month ago. It's been perfect up until then. I observe the same results in terminator and xterm. I'm using zsh if that makes any difference.

#### Neofetch version

Neofetch version 6.0.0-1

## Screenshot

![screenshot_20190121_174238](https://user-images.githubusercontent.com/3089512/51490448-29393300-1da3-11e9-8a0f-8b44f0566e31.png)

## Config file

not relevant?

## Verbose log

https://pastebin.com/BJNrJRBm

**Comment by jamesrobb** [comment]
Is there some "hack" I can use in the mean time to fix this?

**Comment by dylanaraps** [comment]
You can set `--gap` to a negative value (`neofetch --gap -20`).

**Comment by jamesrobb** [comment]
Works! Thanks :)

**Comment by testerfr810** [comment]
Terminator image no work

i have modify rc.conf, scope.sh too
definitely no work on Terminator and Kconsole image

**Comment by dylanaraps** [comment]
Fixed.

**Comment by waltereikrem** [comment]
still an issue. randomly happened to me today. had to make an alian for neofetch and set gap to -50

**Comment by dylanaraps** [comment]
The fix is in the next version.
