### ISSUE TITLE
Unnecessary blank lines after cols ("color bars"), problems using multiple color bars together

### ISSUE THREAD

**Issue by jmccorm** [dylanaraps/neofetch#1209]
**What I wanted (in everyday words):** I wanted neofetch to display a colorful set of bars to visually demonstrate that the ordinary ANSI 16 color mode is working. (That's colors 0 through 15.) Below that, I also wanted neofetch to show if the extended ANSI 256 color mode was working (by rendering 24 more shades of gray with colors colors 232 through 255).

**What I wanted (in technical terms):** To display big block_width=4 blocks of colors 0-15 (which I see that the code has been specifically enhanced to do). Directly below that (with no additional blank lines) I wanted a section with 24 grayscale blocks in the color range of 232 to 255. (Visually, it probably looks better if I just do 235 to 250 with a block_width of 2, but that's a creative choice.)

**What actually happens:** I get my colors 0-15 in two lines (as expected), two blank lines (not unexpected or wanted), and one line of grayscale (as expected).

![putty256](https://user-images.githubusercontent.com/18018091/53701441-fda66100-3dc2-11e9-961e-da23e4d9cb9f.png)

**Additional info:** I tried doing just an ordinary color bar of 0-7, followed by another ordinary color bar of 8-15, and then another color bar of 235-250, but each bar had two blank lines in between them. I think that the cols routing may be inserting more blank lines into its output than is necessary.

**Request:**  I'd like to be able to display my custom color bars and then immediately use the next line for other purposes (which in my case, that would be to display even more color bars).

**Sample Configuration:**
```
    info "Terminal" term
    info "CPU" cpu
    info "CPU Usage" cpu_usage
    info "Memory" memory
    info "Users" users

    # Standard colorblocks (8 dim, 8 bright)
    block_range=(0 15)
    block_width=4
    block_height=1
    info cols
    # Extended ANSI grayscale color blocks
    block_range=(235 250)
    block_width=2
    block_height=1
    info cols
```
PS: Thanks, all. Nice utility! I'm really pleased with neofetch.

**Comment by zver43** [comment]
![AL-1904-4-GD-2019-07-07__09-52-02](https://user-images.githubusercontent.com/44838393/60765712-48085900-a0a7-11e9-8bed-8eab45235f6a.png)


! PS  ! i have only tested it on ArchLinux based distro ! ! 

First step  -> 
to achieve the "goal" to get this  visual i took a "brute-force approach" 
and edit neofetch source directly on Arch-based system 
depends ? but i have it system Files usr/bin/neofetch 

LINE 3393   -in my text editor - i edit that line  by delete " \n\n  " - new line flags(code

`      printf '\n\e[%bC%b' "$text_padding" "${zws}${cols}"   `  

disable 
`       #printf '\n\e[%bC%b\n\n' "$text_padding" "${zws}${cols}" `
 

! but be aware - the prompt line may overlap with Ascii or INFO lines in output/terminal  
needs some tuning :)

Second step ->
add this block of code into  ~/.config/neofetch/config.conf
  .... 
   
    #info cols
    #info line_break
    # Standard colorblocks (8 dim, 8 bright)
    block_range=(0 15)
    block_width=4
    block_height=1
    info cols
    # Extended ANSI grayscale color blocks
    block_range=(235 250)
    block_width=2
    block_height=1
    info cols
    # Extended ANSI grayscale color blocks 2
    block_range=(232 247)
    block_width=2
    block_height=1
    info cols
    # Extended ANSI grayscale color blocks 3
    block_range=(224 256)
    block_width=1
    block_height=1
    info cols
 }
......... 
----------------------------
these extra (color blocks 2) * and (color blocks 3) are un relevant - just for test 
to show scrot

**Comment by dylanaraps** [comment]
This should be fixed in master.

**Comment by microfx** [comment]
What do you mean should? How can I check because on my watch it's 2024 and it's still the same for me.
