### ISSUE TITLE
Resolution display wrong for multi-monitor on Windows 10

### ISSUE THREAD

**Issue by darkstar** [dylanaraps/neofetch#1297]
## Description

When running neofetch on Windows 10 with multiple monitors, the display resolution output is wrong:

```

$ neofetch
                                ..,   user@hostname
                    ....,,:;+ccllll   ---------------
      ...,,+:;  cllllllllllllllllll   OS: Windows 10 Enterprise x86_64
,cclllllllllll  lllllllllllllllllll   Host: Dell Inc. Precision 7530
llllllllllllll  lllllllllllllllllll   Kernel: 2.11.2(0.329/5/3)
llllllllllllll  lllllllllllllllllll   Uptime: 47 mins
llllllllllllll  lllllllllllllllllll   Shell: bash 4.4.23
llllllllllllll  lllllllllllllllllll   Resolution: 19201920x10801200
llllllllllllll  lllllllllllllllllll   DE: Aero
                                      Terminal: mintty
llllllllllllll  lllllllllllllllllll   CPU: Intel i7-8750H (12) @ 2.208GHz
llllllllllllll  lllllllllllllllllll   GPU: Intel(R) UHD Graphics 630 NVIDIA Quadro P1000
llllllllllllll  lllllllllllllllllll   Memory: 7012MiB / 16141MiB
llllllllllllll  lllllllllllllllllll
llllllllllllll  lllllllllllllllllll
`'ccllllllllll  lllllllllllllllllll
       `' \*::  :ccllllllllllllllll
                       ````''*::cll
                                 ``
```

In my case, I have two monitors: 1920x1200 and 1920x1080

#### Neofetch version

Neofetch 6.0.1 (from git 780263f6e6b7c310d39b455cb8778fde324c690f)

## Screenshot
see above

## Config file
none

## Verbose log

[neofetchlog.gz](https://github.com/dylanaraps/neofetch/files/3455489/neofetchlog.gz)

**Comment by Luflosi** [comment]
I'm having the same issue.
`wmic path Win32_VideoController get CurrentHorizontalResolution` prints
```
CurrentHorizontalResolution
1280
1920

```
I'm not good enough with bash to come up with a fix on my own but I'd be happy to help if I can. Let me know what I can do.

**Comment by dylanaraps** [comment]
I need the outputs of these commands:

```sh
wmic path Win32_VideoController get CurrentHorizontalResolution
wmic path Win32_VideoController get CurrentVerticalResolution
```

**Comment by Luflosi** [comment]
I'm using a different setup now but the problem is still the same.
Output of `neofetch` (some fields replaced with x for privacy):
```
                                ..,   DE+x@x 
                    ....,,:;+ccllll   ---------------------- 
      ...,,+:;  cllllllllllllllllll   OS: Windows 10 Enterprise x86_64 
,cclllllllllll  lllllllllllllllllll   Host: x 
llllllllllllll  lllllllllllllllllll   Kernel: x 
llllllllllllll  lllllllllllllllllll   Uptime: x 
llllllllllllll  lllllllllllllllllll   Shell: bash 4.4.23 
llllllllllllll  lllllllllllllllllll   Resolution: 192019201920x108010801080 
llllllllllllll  lllllllllllllllllll   DE: Aero 
                                      CPU: x 
llllllllllllll  lllllllllllllllllll   GPU: x 
llllllllllllll  lllllllllllllllllll   Memory: x 
llllllllllllll  lllllllllllllllllll
llllllllllllll  lllllllllllllllllll                           
llllllllllllll  lllllllllllllllllll
`'ccllllllllll  lllllllllllllllllll
       `' \*::  :ccllllllllllllllll
                       ````''*::cll
                                 ``

```

Output of `wmic path Win32_VideoController get CurrentHorizontalResolution`:
```
CurrentHorizontalResolution  
1920                         
                             
1920                         
1920                         

```
Output of `wmic path Win32_VideoController get CurrentVerticalResolution`:
```
CurrentVerticalResolution  
1080                       
                           
1080                       
1080                       

```

**Comment by dylanaraps** [comment]
Fixed in the latest commit. Please try it and let me know.

**Comment by Luflosi** [comment]
Now no Resolution is printed anymore. Apparently `maparray` isn't available. Is it a program that I need to install?

**Comment by dylanaraps** [comment]
Fixed. Try the latest commit again.

**Comment by Luflosi** [comment]
Unfortunately it's still broken. If I execute
```bash
IFS=$'\n' read -d "" -ra sw \
    < <(wmic path Win32_VideoController get CurrentHorizontalResolution)
```
directly, I get `bash: /dev/fd/62: No such file or directory`.

**Comment by dylanaraps** [comment]
OK, 2 seconds.

**Comment by dylanaraps** [comment]
Try this commit. :+1:

**Comment by Luflosi** [comment]
Almost: `Resolution: xCurrentVerticalResolution,1920x1080,x,1920x1080,1920x1080`.
Thanks for the quick responses btw.

**Comment by dylanaraps** [comment]
No problem. Another minute or so...

**Comment by dylanaraps** [comment]
Try now. :+1:

**Comment by Luflosi** [comment]
One step closer: `Resolution: x,1920x1080,x,1920x1080,1920x1080`. 👍

**Comment by dylanaraps** [comment]
Heh! Alright.

**Comment by dylanaraps** [comment]
Try now. :+1:

**Comment by Luflosi** [comment]
Now one monitor is missing: `Resolution: 1920x1080,1920x1080`.
I am a bit confused though. It's a Laptop with two external monitors. All three monitors have a resolution of 1920x1080. When I close the lid, the Windows preferences only show the two external monitors but `wmic path Win32_VideoController get CurrentHorizontalResolution` still prints three numbers. If I use the Windows preferences to change the resolution of one monitor, the command output stays the same.
Anyways, I think neofetch should print all six numbers from the two commands.

**Comment by dylanaraps** [comment]
Try the latest commit. :+1:

**Comment by Luflosi** [comment]
Now it works as expected: `Resolution: 1920x1080, 1920x1080, 1920x1080` 🎉.
Thank you for the fix(es) ❤️.

**Comment by dylanaraps** [comment]
No problem. :)
