### ISSUE TITLE
Empty lines at end

### ISSUE THREAD

**Issue by Carl-Marx** [dylanaraps/neofetch#816]
## Description
Hello,
I would like to know how to remove the empty lines at the end.

#### Neofetch version
3.2.0-1

## Screenshot
![deepinscreenshot_deepin-terminal_20170826173715](https://user-images.githubusercontent.com/19856591/29744936-3a01f044-8a85-11e7-9ca8-966d6cb428de.png)

## Config file
https://pastebin.com/wTXCN5GK

## Verbose log
https://pastebin.com/vRgULGtM

**Comment by dylanaraps** [comment]
Fixed.

**Comment by microfx** [comment]
It's not fixed...? How can I remove them?

**Comment by repoles** [comment]
Indeed, it's not fixed.
![CleanShot 2024-03-04 at 09 55 32@2x](https://github.com/dylanaraps/neofetch/assets/1004592/4f388c13-a122-4bca-9e41-be2c6bd0031a)

**Comment by andev0** [comment]
Possible workaround: `neofetch | head -n -2`
It will remove last two lines from the output of `neofetch`
