### ISSUE TITLE
Image not showing iTerm2

### ISSUE THREAD

**Issue by kelaun** [dylanaraps/neofetch#844]
## Description

Neofetch in iTerm2 is not showing an image, but a placeholder.

#### Neofetch version
3.3.0

## Screenshot
<img width="854" alt="neofetch_bug" src="https://user-images.githubusercontent.com/11407575/31617448-84d6e3d6-b28f-11e7-86a7-475e5f025fe1.png">

## Config file
Default config (running with --backend iterm2 --source <path_to_image>

## Verbose log
[neofetchlog.txt](https://pastebin.com/rHrSV62R)

**Comment by dylanaraps** [comment]
The image you're trying to use doesn't exist. The log file tells me that Neofetch can't find the image.

**Comment by kelaun** [comment]
Hello,

The image is there. I just had a look.
<img width="575" alt="bug1" src="https://user-images.githubusercontent.com/11407575/31655733-1e42da3a-b32a-11e7-9fed-8eb566e688a5.png">
<img width="568" alt="bug2" src="https://user-images.githubusercontent.com/11407575/31655734-1e5a2fd2-b32a-11e7-9485-f279e5764a58.png">

Here you can see that the folder and file exist.

**Comment by iandrewt** [comment]
I'm able to reproduce this with every image I try, and it doesn't seem to be an issue with iTerm2 because `imgcat` works on its own.

**Comment by iandrewt** [comment]
Looks like the issue is actually in the thumbnail conversion, this seems to be the relevant section of the log:

```bash
+ convert -background none '/Library/Desktop Pictures/Rolling Waves.jpg' -gravity center -crop 2880x2880+0+0 -quality 95 -scale 810x810 '/Users/andrew/.cache/thumbnails/neofetch/normal-center-810-810-/Library/Desktop Pictures/Rolling Waves.jpg.jpg'
convert: unable to open image '/Users/andrew/.cache/thumbnails/neofetch/normal-center-810-810-/Library/Desktop Pictures/Rolling Waves.jpg.jpg': No such file or directory @ error/blob.c/OpenBlob/3146.
+ image='/Users/andrew/.cache/thumbnails/neofetch/normal-center-810-810-/Library/Desktop Pictures/Rolling Waves.jpg.jpg'
+ display_image
+ case "$image_backend" in
++ base64
./neofetch: line 2771: /Users/andrew/.cache/thumbnails/neofetch/normal-center-810-810-/Library/Desktop Pictures/Rolling Waves.jpg.jpg: No such file or directory
```

**Comment by kelaun** [comment]
@iandrewt In your extract it seems it is looking for an image with *.jpg.jpg
Therefore I already tried making the image file without any extension, but it is still not working.

**Comment by iandrewt** [comment]
Oddly, this issue isn't occurring on my MacBook, only my hackintosh (which doesn't have macOS on it at the moment so I can't retest). I'm thinking it may be related to the iTerm2 version? On my MacBook, I have Build 3.1.20170913-nightly, whereas the Hackintosh had 3.1.3. Might try updating iTerm2 and seeing if the issue reoccurs on my MacBook

**Comment by hankerboy** [comment]
**OS:** Mac OS Sierra 10.12.6 (16G29)
**Device:** MacBook Pro (Retina, 13-inch, Early 2015)
**iTerm2 Version:** Build 3.1.20171005-nightly
Same issue, I tried providing absolute path, reinstalling neofetch and providing images with different extensions, but it doesn't help. When I try doing `imgcat /path/to/image.png` it works

<img width="752" alt="1" src="https://user-images.githubusercontent.com/31503345/31851360-093b5324-b66d-11e7-89a0-d54e57186eb5.png">
<img width="752" alt="2" src="https://user-images.githubusercontent.com/31503345/31851361-095c38aa-b66d-11e7-89a3-006db98864d4.png">
<img width="752" alt="3" src="https://user-images.githubusercontent.com/31503345/31851362-0980776a-b66d-11e7-8ef2-ce36babfe21c.png">

**Comment by jorgegonzalez** [comment]
Seemingly related issue here when running `neofetch --iterm2`

![image](https://user-images.githubusercontent.com/12901172/31892374-db7721d2-b7d6-11e7-90ab-3f3f4e8f71dc.png)

**Comment by Mihaly-Ma** [comment]
when neofetch call convert it will raise an error said unable to open the target file, seems like convert cannot create multiple dirs. if i create the dir it needs in ~/.cache/thumbnails/neofetch. it works.

**Comment by konimex** [comment]
Does #872 fix your issues?

@kelaun @hankerboy 

CC: @iandrewt

**Comment by hankerboy** [comment]
@konimex It does

**Comment by hankerboy** [comment]
@konimex It does, but text becomes weird
![image](https://user-images.githubusercontent.com/31503345/33241670-c4088f86-d2d9-11e7-997a-ee05ac0546c3.png)

**Comment by mollax** [comment]
It seems that regular expressions behave differently in mac default bash (3.2.57).
In the make_thumbnail function
```
make_thumbnail() {
    # Name the thumbnail using variables so we can
    # use it later.
    image_name="$crop_mode-$crop_offset-$width-$height-${image//'/'/_}"
```

change to 
```
make_thumbnail() {
    # Name the thumbnail using variables so we can
    # use it later.
    image_name="$crop_mode-$crop_offset-$width-$height-${image//\//_}"
```

**Comment by mollax** [comment]
@hankerboy @jorgegonzalez add some blank characters (in prin() function).
```
    # Print the info.
    printf "%b\n" "${text_padding:+\033[${text_padding}C}${zws}${string}${reset}"
```
change to
```
    # Print the info.
    printf "%b\n" "${text_padding:+\033[${text_padding}C}${zws}${string}${reset}    "
```

**Comment by konimex** [comment]
Ah.. So that's why the space was originally added. I originally removed it in #799 so that may trigger the fault. After I'll get home I'll test #872 to see if it works in Linux (or really, any OS with newer bash) as well. Also, I'll add whitespace back in `get_underline` and `prin` function.

**Comment by hankerboy** [comment]
@mollax It works
![image](https://user-images.githubusercontent.com/31503345/33266040-0358a29c-d385-11e7-89fb-de6610e85e7f.png)

**Comment by konimex** [comment]
Since #872 has been merged and the garbage output problem has been solved, I'm closing this.

**Comment by mike3run** [comment]
I still have this problem on Mac do I need to update in a specific way to have #872 in my system?

**Comment by mike3run** [comment]
for more info here's my pastebin: https://pastebin.com/DUJtChtF

But really my symptoms are exactly as the ones described in this issue 😢

**Comment by konimex** [comment]
Did you use the `-git` version?

**Comment by mike3run** [comment]
@konimex no I installed via Homebrew you mean install directly via this repo?

**Comment by jorgegonzalez** [comment]
@mike3run Clone this repo and run it.

**Comment by mike3run** [comment]
when cloning the repo it works but it looks like some characters are not being escaped properly or something here's how it looks running from `./neofetch`

<img width="1214" alt="screen shot 2017-12-30 at 11 34 01 am" src="https://user-images.githubusercontent.com/7088511/34456165-85e81140-ed55-11e7-969c-99d748c713da.png">


### Pastebin
https://pastebin.com/VRbevGW5

**Comment by jorgegonzalez** [comment]
I'm having the same issue as @mike3run.

**Comment by konimex** [comment]
Try to test this (as I can't because I have no Mac):

Add a single whitespace in line 2382:

` printf "%b\n" "\\e[${text_padding}C${zws}${cols}"`

to

` printf "%b\n" "\\e[${text_padding}C${zws}${cols} "`

**Comment by mike3run** [comment]
<img width="1214" alt="screen shot 2017-12-30 at 7 19 43 pm" src="https://user-images.githubusercontent.com/7088511/34458382-6cce12b8-ed96-11e7-9944-2bdea343a1f6.png">

@konimex that added the space after the color scheme but the unescaped sequence seems to still be there 😢

**Comment by konimex** [comment]
Yep. That's a different issue.

Try to open up a new issue as this one's a separate bug.

**Comment by mike3run** [comment]
@konimex alright: https://github.com/dylanaraps/neofetch/issues/890
